# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da1ea658a883d9b0617f08e28f31ce10601cc3a1cecd6de4902c437859a176a6d0bfa51d9085ea442131a42149a96ea5f139ce4e57a3eccb6fc2a86919b4b914

test:
  secret_key_base: 0275e21fadeb445ade411327ea23a61296e33aed65ec5a08697bf241e20dbcf3fb45c4c35a097e77370638f7ea7a03ac50e44dddcaf5834a5cdb11e4abb85353

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
